# Generated by Django 2.1.7 on 2019-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20190320_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
