# Generated by Django 2.1.7 on 2019-03-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20190320_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MattUpload',
        ),
    ]
