# Generated by Django 2.1.7 on 2019-03-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_auto_20190320_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
