# Generated by Django 2.1.7 on 2019-03-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_auto_20190320_0609'),
        ('uploads', '0002_auto_20190320_1809'),
    ]

    operations = [
    ]
