# Generated by Django 2.1.7 on 2019-03-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('frequency', models.FloatField(null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
                ('word_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngram_word_one', to='words.Word')),
                ('word_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngram_word_three', to='words.Word')),
                ('word_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngram_word_two', to='words.Word')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ngram',
            unique_together={('word_one', 'word_two', 'word_three')},
        ),
    ]
