# Generated by Django 2.1.7 on 2019-03-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram_start', models.TextField(db_index=True)),
                ('ngram_end', models.TextField()),
                ('count', models.IntegerField()),
                ('frequency', models.FloatField(null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.Language')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ngram',
            unique_together={('ngram_start', 'ngram_end')},
        ),
    ]
