# Generated by Django 2.1.7 on 2019-03-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20190319_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='length',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
